###
// Inscription
POST http://localhost:9191/api/inscription
Content-Type: application/json

{
  "email": "accueil@chillo.tech",
  "mdp": "accueil",
  "nom": "Accueil"
}

###
POST http://localhost:9191/api/activation
Content-Type: application/json

{
  "email": "accueil@chillo.tech",
  "code": "876756"
}

###
POST http://localhost:9191/api/connexion
Content-Type: application/json

{
  "username": "accueil@chillo.tech",
  "password": "accueil"
}

###
// Login admin
POST http://localhost:9191/api/connexion
Content-Type: application/json

{
  "username": "achille.mbougueng@chillo.tech",
  "password": "admin"
}


###
// Login manager
POST http://localhost:9191/api/connexion
Content-Type: application/json

{
  "username": "manager@chillo.tech",
  "password": "manager"
}

###

###
// Admin
GET http://localhost:9191/api/utilisateur
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MDAyOTExNDIsIm5vbSI6ImFkbWluIiwic3ViIjoiYWNoaWxsZS5tYm91Z3VlbmdAY2hpbGxvLnRlY2gifQ.KV5RfayENkJc6tAhEytSOM74sRGyGGqDCtLdgmL84CU


###
// Manager
GET http://localhost:9191/api/utilisateur
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MDAyOTEyNjQsIm5vbSI6Im1hbmFnZXIiLCJzdWIiOiJtYW5hZ2VyQGNoaWxsby50ZWNoIn0.Ey5f8QHr-k6X9Xek4kUbFQkl2E22Cx5jnxvkOZDQffY


###
// Utilisateur
GET http://localhost:9191/api/utilisateur
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MDAyOTExOTIsIm5vbSI6IkFjY3VlaWwiLCJzdWIiOiJhY2N1ZWlsQGNoaWxsby50ZWNoIn0._-yJJ5hcEyH5YDaDvhGD-09uqzneH35-zXYQ_esOnR8
